# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               阳阳
tagline:             'Since 2016.2.18'
description:         'Website to record the bright life of yang yang.'
url:                 https://initlove.github.io
baseurl:             'https://initlove.github.io'
paginate:            5

# About/contact
author:
  name:              我们都爱阳阳
  url:               initlove.github.io
  email:             liangchenye@gmail.com

# Custom vars
version:             0.1.0
